version: '3.0'

services:
  nginx:
    depends_on:
      - node
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  node:
    build:
      dockerfile: Dockerfile
      context: ./node
    ports:
      - "3000"
    volumes:
      - /app/node_modules:/app/node_modules
      - ./client:/app